"""Auth — JWT/Clerk providers, Apple IAP entitlements, and a FastAPI Depends factory."""
import base64
import json
import time
import uuid
from datetime import datetime, timezone
from functools import lru_cache
from pathlib import Path
from typing import Optional

from pydantic import BaseModel


class User(BaseModel):
    id: str
    org_id: Optional[str] = None
    org_slug: Optional[str] = None
    org_role: Optional[str] = None
    org_permissions: Optional[list] = None
    plan: Optional[str] = None
    features: Optional[list] = None


class JWT:
    """JWT provider with dev/prod URL pairs. dev falls back to prod when omitted."""

    def __init__(self, jwks_url, dev_jwks_url=None):
        self.jwks_url = jwks_url
        self.dev_jwks_url = dev_jwks_url or jwks_url

    def resolve(self, prod):
        return {"jwks_url": self.jwks_url if prod else self.dev_jwks_url}

    def claims_to_user(self, decoded) -> "User":
        return User(id=decoded.get("sub"))


class Clerk(JWT):
    """Clerk provider with hosted defaults; pass explicit URLs to override."""
    _JWKS     = "https://clerk.cycls.ai/.well-known/jwks.json"
    _DEV_JWKS = "https://select-sloth-58.clerk.accounts.dev/.well-known/jwks.json"
    _PK       = "pk_live_Y2xlcmsuY3ljbHMuYWkk"
    _DEV_PK   = "pk_test_c2VsZWN0LXNsb3RoLTU4LmNsZXJrLmFjY291bnRzLmRldiQ"

    def __init__(self, *, jwks_url=None, dev_jwks_url=None, pk=None, dev_pk=None):
        super().__init__(jwks_url or self._JWKS, dev_jwks_url or self._DEV_JWKS)
        self.pk = pk or self._PK
        self.dev_pk = dev_pk or self._DEV_PK

    def resolve(self, prod):
        return {**super().resolve(prod), "pk": self.pk if prod else self.dev_pk}

    def claims_to_user(self, decoded) -> "User":
        org = decoded.get("o") or {}
        fea = decoded.get("fea")
        if isinstance(fea, str):
            fea = [f.strip() for f in fea.split(",") if f.strip()]
        return User(
            id=decoded.get("sub"), plan=decoded.get("pla"), features=fea,
            org_id=org.get("id"), org_slug=org.get("slg"),
            org_role=org.get("rol"), org_permissions=org.get("per"),
        )


class GCP(JWT):
    """GCP Identity Platform / Firebase Auth.
    Maps `firebase.tenant` → `org_id` so multi-tenant projects share workspace
    semantics with Clerk orgs (org-shared root, per-user DB)."""

    def __init__(self, project_id, *, jwks_url=None):
        super().__init__(jwks_url or
            "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com")
        self.project_id = project_id

    def claims_to_user(self, decoded) -> "User":
        tenant = (decoded.get("firebase") or {}).get("tenant")
        return User(id=decoded.get("sub"), org_id=tenant)


# ---- Apple IAP entitlement (StoreKit 2 JWS verification) ----

_APPLE_ROOT = Path(__file__).parent / "AppleRootCA-G3.cer"
_OID_LEAF = "1.2.840.113635.100.6.11.1"    # Apple receipt/transaction signing
_OID_INTERMEDIATE = "1.2.840.113635.100.6.2.1"


def _b64(s: str) -> bytes:
    return base64.urlsafe_b64decode(s + "=" * (-len(s) % 4))


class AppleIAP:
    """Offline verification of a StoreKit 2 signed transaction (JWS) sent in a
    header — proves the request comes from an active subscriber. The
    transaction's appAccountToken, UUIDv5(namespace, user_id) generated by the
    client at purchase, binds it to the authenticated user so a token can't be
    replayed by another account. The x5c chain is validated against the bundled
    Apple Root CA G3; fails closed on anything unexpected.

        iap = AppleIAP(bundle_id="com.example.app",
                       products={"com.example.app.pro.monthly"},
                       namespace="<uuid the client also uses>")
    """

    def __init__(self, bundle_id, products, namespace, plan="u:iap",
                 header="x-apple-entitlement", root_cert: bytes | None = None):
        self.bundle_id = bundle_id
        self.products = set(products)
        self.namespace = uuid.UUID(str(namespace))
        self.plan = plan
        self.header = header
        self.root_der = root_cert or _APPLE_ROOT.read_bytes()

    def _decode(self, jws: str) -> dict:
        """Verify the JWS end-to-end and return its payload. Raises on any failure."""
        from cryptography import x509
        from cryptography.hazmat.primitives import hashes, serialization
        from cryptography.hazmat.primitives.asymmetric import ec
        from cryptography.hazmat.primitives.asymmetric.utils import encode_dss_signature

        h64, p64, s64 = jws.split(".")
        header = json.loads(_b64(h64))
        if header.get("alg") != "ES256":
            raise ValueError("alg")
        chain = [x509.load_der_x509_certificate(base64.b64decode(c)) for c in header["x5c"]]
        if len(chain) != 3:
            raise ValueError("chain length")
        leaf, inter, root = chain
        if root.public_bytes(serialization.Encoding.DER) != self.root_der:
            raise ValueError("untrusted root")
        inter.verify_directly_issued_by(root)
        leaf.verify_directly_issued_by(inter)
        now = datetime.now(timezone.utc)
        for c in chain:
            if not (c.not_valid_before_utc <= now <= c.not_valid_after_utc):
                raise ValueError("cert expired")
        if _OID_LEAF not in {e.oid.dotted_string for e in leaf.extensions}:
            raise ValueError("leaf oid")
        if _OID_INTERMEDIATE not in {e.oid.dotted_string for e in inter.extensions}:
            raise ValueError("intermediate oid")
        sig = _b64(s64)
        der = encode_dss_signature(int.from_bytes(sig[:32], "big"), int.from_bytes(sig[32:], "big"))
        leaf.public_key().verify(der, f"{h64}.{p64}".encode(), ec.ECDSA(hashes.SHA256()))
        return json.loads(_b64(p64))

    def verify(self, jws, user_id) -> bool:
        """True iff *jws* is a valid, unexpired, unrevoked transaction for one of
        our products, purchased by *user_id*. Never raises."""
        try:
            t = self._decode(jws)
            return (t.get("bundleId") == self.bundle_id
                    and t.get("productId") in self.products
                    and t.get("appAccountToken") == str(uuid.uuid5(self.namespace, user_id))
                    and (t.get("expiresDate") or 0) > time.time() * 1000
                    and t.get("revocationDate") is None)
        except Exception:
            return False

    def apply(self, user, headers):
        """Upgrade *user*'s plan for this request when a valid entitlement header
        is present. Org-scoped plans are left alone (org billing is separate)."""
        jws = headers.get(self.header)
        if not (jws and user and user.id):
            return
        if user.plan and not user.plan.startswith("u:"):
            return
        if self.verify(jws, user.id):
            user.plan = self.plan


@lru_cache(maxsize=8)
def _jwks_client(url):
    from jwt import PyJWKClient
    return PyJWKClient(url)


def authenticate(provider, prod, token: str) -> User:
    """Decode *token* via *provider*'s JWKS; return a User. Raises on failure."""
    import jwt as jwtlib
    jwks_url = provider.resolve(prod)["jwks_url"] if provider else None
    if not jwks_url:
        raise RuntimeError("Auth not configured (missing JWKS URL)")
    key = _jwks_client(jwks_url).get_signing_key_from_jwt(token)
    decoded = jwtlib.decode(token, key.key, algorithms=["RS256"], leeway=10)
    return provider.claims_to_user(decoded)


def validator(provider, prod, iap=None):
    from fastapi import Depends, HTTPException, Request
    from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials

    def validate(
        request: Request,
        bearer: Optional[HTTPAuthorizationCredentials] = Depends(HTTPBearer(auto_error=False)),
    ) -> User:
        if not bearer:
            raise HTTPException(401, "Not authenticated", headers={"WWW-Authenticate": "Bearer"})
        try:
            user = authenticate(provider, prod, bearer.credentials)
        except RuntimeError as e:
            raise HTTPException(500, str(e))
        except Exception as e:
            raise HTTPException(401, str(e), headers={"WWW-Authenticate": "Bearer"})
        if iap is not None:
            iap.apply(user, request.headers)
        return user

    return validate
